/*
 * This file is generated by jOOQ.
 */
package com.example.demofx;


import com.example.demofx.tables.Diagnostic;
import com.example.demofx.tables.Follow;
import com.example.demofx.tables.Patient;
import com.example.demofx.tables.Role;
import com.example.demofx.tables.Service;
import com.example.demofx.tables.Type;
import com.example.demofx.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Doctorlite extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>doctorlite</code>
     */
    public static final Doctorlite DOCTORLITE = new Doctorlite();

    /**
     * The table <code>doctorlite.diagnostic</code>.
     */
    public final Diagnostic DIAGNOSTIC = Diagnostic.DIAGNOSTIC;

    /**
     * The table <code>doctorlite.follow</code>.
     */
    public final Follow FOLLOW = Follow.FOLLOW;

    /**
     * The table <code>doctorlite.patient</code>.
     */
    public final Patient PATIENT = Patient.PATIENT;

    /**
     * The table <code>doctorlite.role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>doctorlite.service</code>.
     */
    public final Service SERVICE = Service.SERVICE;

    /**
     * The table <code>doctorlite.type</code>.
     */
    public final Type TYPE = Type.TYPE;

    /**
     * The table <code>doctorlite.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Doctorlite() {
        super("doctorlite", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Diagnostic.DIAGNOSTIC,
            Follow.FOLLOW,
            Patient.PATIENT,
            Role.ROLE,
            Service.SERVICE,
            Type.TYPE,
            User.USER
        );
    }
}
