/*
 * This file is generated by jOOQ.
 */
package com.example.demofx.databaseManger.jooq;


import com.example.demofx.databaseManger.jooq.tables.Diagnostic;
import com.example.demofx.databaseManger.jooq.tables.Follow;
import com.example.demofx.databaseManger.jooq.tables.Patient;
import com.example.demofx.databaseManger.jooq.tables.Role;
import com.example.demofx.databaseManger.jooq.tables.Service;
import com.example.demofx.databaseManger.jooq.tables.Type;
import com.example.demofx.databaseManger.jooq.tables.User;


/**
 * Convenience access to all tables in doctorlite.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>doctorlite.diagnostic</code>.
     */
    public static final Diagnostic DIAGNOSTIC = Diagnostic.DIAGNOSTIC;

    /**
     * The table <code>doctorlite.follow</code>.
     */
    public static final Follow FOLLOW = Follow.FOLLOW;

    /**
     * The table <code>doctorlite.patient</code>.
     */
    public static final Patient PATIENT = Patient.PATIENT;

    /**
     * The table <code>doctorlite.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>doctorlite.service</code>.
     */
    public static final Service SERVICE = Service.SERVICE;

    /**
     * The table <code>doctorlite.type</code>.
     */
    public static final Type TYPE = Type.TYPE;

    /**
     * The table <code>doctorlite.user</code>.
     */
    public static final User USER = User.USER;
}
