/*
 * This file is generated by jOOQ.
 */
package com.example.demofx.databaseManger.jooq.tables.records;


import com.example.demofx.databaseManger.jooq.tables.Patient;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatientRecord extends UpdatableRecordImpl<PatientRecord> implements Record14<Long, String, String, String, String, String, String, String, String, String, Integer, LocalDate, Integer, Double> {

    private static final long serialVersionUID = 1L;


    /**
     * Setter for <code>doctorlite.patient.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>doctorlite.patient.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>doctorlite.patient.firstName</code>.
     */
    public void setFirstname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>doctorlite.patient.firstName</code>.
     */
    public String getFirstname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>doctorlite.patient.lastName</code>.
     */
    public void setLastname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>doctorlite.patient.lastName</code>.
     */
    public String getLastname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>doctorlite.patient.phone</code>.
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>doctorlite.patient.phone</code>.
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>doctorlite.patient.address</code>.
     */
    public void setAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>doctorlite.patient.address</code>.
     */
    public String getAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>doctorlite.patient.civilStatus</code>.
     */
    public void setCivilstatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>doctorlite.patient.civilStatus</code>.
     */
    public String getCivilstatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>doctorlite.patient.worke</code>.
     */
    public void setWorke(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>doctorlite.patient.worke</code>.
     */
    public String getWorke() {
        return (String) get(6);
    }

    /**
     * Setter for <code>doctorlite.patient.scientificLevel</code>.
     */
    public void setScientificlevel(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>doctorlite.patient.scientificLevel</code>.
     */
    public String getScientificlevel() {
        return (String) get(7);
    }

    /**
     * Setter for <code>doctorlite.patient.socioEconomicLevel</code>.
     */
    public void setSocioeconomiclevel(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>doctorlite.patient.socioEconomicLevel</code>.
     */
    public String getSocioeconomiclevel() {
        return (String) get(8);
    }

    /**
     * Setter for <code>doctorlite.patient.gender</code>.
     */
    public void setGender(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>doctorlite.patient.gender</code>.
     */
    public String getGender() {
        return (String) get(9);
    }

    /**
     * Setter for <code>doctorlite.patient.age</code>.
     */
    public void setAge(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>doctorlite.patient.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>doctorlite.patient.birthday</code>.
     */
    public void setBirthday(LocalDate value) {
        set(11, value);
    }

    /**
     * Getter for <code>doctorlite.patient.birthday</code>.
     */
    public LocalDate getBirthday() {
        return (LocalDate) get(11);
    }
    public String getBirthdayString() {
        return getBirthday().toString() ;
    }

    /**
     * Setter for <code>doctorlite.patient.height</code>.
     */
    public void setHeight(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>doctorlite.patient.height</code>.
     */
    public Integer getHeight() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>doctorlite.patient.wieght</code>.
     */
    public void setWieght(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>doctorlite.patient.wieght</code>.
     */
    public Double getWieght() {
        return (Double) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, String, String, String, String, String, String, String, String, String, Integer, LocalDate, Integer, Double> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, String, String, String, String, String, String, String, String, String, Integer, LocalDate, Integer, Double> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Patient.PATIENT.ID;
    }

    @Override
    public Field<String> field2() {
        return Patient.PATIENT.FIRSTNAME;
    }

    @Override
    public Field<String> field3() {
        return Patient.PATIENT.LASTNAME;
    }

    @Override
    public Field<String> field4() {
        return Patient.PATIENT.PHONE;
    }

    @Override
    public Field<String> field5() {
        return Patient.PATIENT.ADDRESS;
    }

    @Override
    public Field<String> field6() {
        return Patient.PATIENT.CIVILSTATUS;
    }

    @Override
    public Field<String> field7() {
        return Patient.PATIENT.WORKE;
    }

    @Override
    public Field<String> field8() {
        return Patient.PATIENT.SCIENTIFICLEVEL;
    }

    @Override
    public Field<String> field9() {
        return Patient.PATIENT.SOCIOECONOMICLEVEL;
    }

    @Override
    public Field<String> field10() {
        return Patient.PATIENT.GENDER;
    }

    @Override
    public Field<Integer> field11() {
        return Patient.PATIENT.AGE;
    }

    @Override
    public Field<LocalDate> field12() {
        return Patient.PATIENT.BIRTHDAY;
    }

    @Override
    public Field<Integer> field13() {
        return Patient.PATIENT.HEIGHT;
    }

    @Override
    public Field<Double> field14() {
        return Patient.PATIENT.WIEGHT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFirstname();
    }

    @Override
    public String component3() {
        return getLastname();
    }

    @Override
    public String component4() {
        return getPhone();
    }

    @Override
    public String component5() {
        return getAddress();
    }

    @Override
    public String component6() {
        return getCivilstatus();
    }

    @Override
    public String component7() {
        return getWorke();
    }

    @Override
    public String component8() {
        return getScientificlevel();
    }

    @Override
    public String component9() {
        return getSocioeconomiclevel();
    }

    @Override
    public String component10() {
        return getGender();
    }

    @Override
    public Integer component11() {
        return getAge();
    }

    @Override
    public LocalDate component12() {
        return getBirthday();
    }

    @Override
    public Integer component13() {
        return getHeight();
    }

    @Override
    public Double component14() {
        return getWieght();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFirstname();
    }

    @Override
    public String value3() {
        return getLastname();
    }

    @Override
    public String value4() {
        return getPhone();
    }

    @Override
    public String value5() {
        return getAddress();
    }

    @Override
    public String value6() {
        return getCivilstatus();
    }

    @Override
    public String value7() {
        return getWorke();
    }

    @Override
    public String value8() {
        return getScientificlevel();
    }

    @Override
    public String value9() {
        return getSocioeconomiclevel();
    }

    @Override
    public String value10() {
        return getGender();
    }

    @Override
    public Integer value11() {
        return getAge();
    }

    @Override
    public LocalDate value12() {
        return getBirthday();
    }

    @Override
    public Integer value13() {
        return getHeight();
    }

    @Override
    public Double value14() {
        return getWieght();
    }

    @Override
    public PatientRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PatientRecord value2(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public PatientRecord value3(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public PatientRecord value4(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public PatientRecord value5(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public PatientRecord value6(String value) {
        setCivilstatus(value);
        return this;
    }

    @Override
    public PatientRecord value7(String value) {
        setWorke(value);
        return this;
    }

    @Override
    public PatientRecord value8(String value) {
        setScientificlevel(value);
        return this;
    }

    @Override
    public PatientRecord value9(String value) {
        setSocioeconomiclevel(value);
        return this;
    }

    @Override
    public PatientRecord value10(String value) {
        setGender(value);
        return this;
    }

    @Override
    public PatientRecord value11(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public PatientRecord value12(LocalDate value) {
        setBirthday(value);
        return this;
    }

    @Override
    public PatientRecord value13(Integer value) {
        setHeight(value);
        return this;
    }

    @Override
    public PatientRecord value14(Double value) {
        setWieght(value);
        return this;
    }

    @Override
    public PatientRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, Integer value11, LocalDate value12, Integer value13, Double value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PatientRecord
     */
    public PatientRecord() {
        super(Patient.PATIENT);
    }

    /**
     * Create a detached, initialised PatientRecord
     */
    public PatientRecord(Long id, String firstname, String lastname, String phone, String address, String civilstatus, String worke, String scientificlevel, String socioeconomiclevel, String gender, Integer age, LocalDate birthday, Integer height, Double wieght) {
        super(Patient.PATIENT);

        setId(id);
        setFirstname(firstname);
        setLastname(lastname);
        setPhone(phone);
        setAddress(address);
        setCivilstatus(civilstatus);
        setWorke(worke);
        setScientificlevel(scientificlevel);
        setSocioeconomiclevel(socioeconomiclevel);
        setGender(gender);
        setAge(age);
        setBirthday(birthday);
        setHeight(height);
        setWieght(wieght);
    }
}
