/*
 * This file is generated by jOOQ.
 */
package com.example.demofx.databaseManger.jooq.tables.records;


import com.example.demofx.databaseManger.jooq.tables.User;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record10<Long, String, String, String, String, String, String, Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>doctorlite.user.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>doctorlite.user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>doctorlite.user.userName</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>doctorlite.user.userName</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>doctorlite.user.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>doctorlite.user.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>doctorlite.user.firstName</code>.
     */
    public void setFirstname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>doctorlite.user.firstName</code>.
     */
    public String getFirstname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>doctorlite.user.lastName</code>.
     */
    public void setLastname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>doctorlite.user.lastName</code>.
     */
    public String getLastname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>doctorlite.user.phone</code>.
     */
    public void setPhone(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>doctorlite.user.phone</code>.
     */
    public String getPhone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>doctorlite.user.type</code>.
     */
    public void setType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>doctorlite.user.type</code>.
     */
    public String getType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>doctorlite.user.idService</code>.
     */
    public void setIdservice(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>doctorlite.user.idService</code>.
     */
    public Long getIdservice() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>doctorlite.user.idRole</code>.
     */
    public void setIdrole(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>doctorlite.user.idRole</code>.
     */
    public Long getIdrole() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>doctorlite.user.idType</code>.
     */
    public void setIdtype(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>doctorlite.user.idType</code>.
     */
    public Long getIdtype() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, String, String, String, String, Long, Long, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, String, String, String, String, String, Long, Long, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.USERNAME;
    }

    @Override
    public Field<String> field3() {
        return User.USER.PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return User.USER.FIRSTNAME;
    }

    @Override
    public Field<String> field5() {
        return User.USER.LASTNAME;
    }

    @Override
    public Field<String> field6() {
        return User.USER.PHONE;
    }

    @Override
    public Field<String> field7() {
        return User.USER.TYPE;
    }

    @Override
    public Field<Long> field8() {
        return User.USER.IDSERVICE;
    }

    @Override
    public Field<Long> field9() {
        return User.USER.IDROLE;
    }

    @Override
    public Field<Long> field10() {
        return User.USER.IDTYPE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getFirstname();
    }

    @Override
    public String component5() {
        return getLastname();
    }

    @Override
    public String component6() {
        return getPhone();
    }

    @Override
    public String component7() {
        return getType();
    }

    @Override
    public Long component8() {
        return getIdservice();
    }

    @Override
    public Long component9() {
        return getIdrole();
    }

    @Override
    public Long component10() {
        return getIdtype();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getFirstname();
    }

    @Override
    public String value5() {
        return getLastname();
    }

    @Override
    public String value6() {
        return getPhone();
    }

    @Override
    public String value7() {
        return getType();
    }

    @Override
    public Long value8() {
        return getIdservice();
    }

    @Override
    public Long value9() {
        return getIdrole();
    }

    @Override
    public Long value10() {
        return getIdtype();
    }

    @Override
    public UserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public UserRecord value5(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public UserRecord value6(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public UserRecord value7(String value) {
        setType(value);
        return this;
    }

    @Override
    public UserRecord value8(Long value) {
        setIdservice(value);
        return this;
    }

    @Override
    public UserRecord value9(Long value) {
        setIdrole(value);
        return this;
    }

    @Override
    public UserRecord value10(Long value) {
        setIdtype(value);
        return this;
    }

    @Override
    public UserRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, Long value8, Long value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Long id, String username, String password, String firstname, String lastname, String phone, String type, Long idservice, Long idrole, Long idtype) {
        super(User.USER);

        setId(id);
        setUsername(username);
        setPassword(password);
        setFirstname(firstname);
        setLastname(lastname);
        setPhone(phone);
        setType(type);
        setIdservice(idservice);
        setIdrole(idrole);
        setIdtype(idtype);
    }
}
